### ISSUE TITLE
외부 package에 대한 wrapper를 구현해야 하는가?

### ISSUE THREAD

**Issue by KangJiJi** [TeamChoiKang/antique-universe-front-end#15]
# 작업

material ui와 react router에 대한 wrapper를 구현해야 하는가?

# 참고사항

없음

**Comment by joi0104** [comment]
저도 코드 보면서 고민을 많이 했는데요... 저희가 이번 프로젝트에서의 목표했던 것중에 `다양한 디자인패턴을 적용해보고 다양한 시도를 해보자!`가 있었으니, 과하더라도 wrapper를 적용해보는 건 어떨까요?
