### ISSUE TITLE
Map tile 적용하기

### ISSUE THREAD

**Issue by KangJiJi** [TeamChoiKang/antique-universe-front-end#32]
## 작업 설명

현재는 이미지를 특정 좌표에 추가하는 형식으로 맵을 구현하고있다. 하지만 이런 방법보다 맵을 tile 단위로 나누어서 맵을 디자인하는 방식이 더 유지보수가 쉽고 새로운 디자인에도 유리하다. 따라서 Tiled 프로그램의 학습과 적용을 하는 것을 고려해봐야 할 것 같다.

## 참고 사항

- [Tile을 사용하는 예시](https://stackabuse.com/phaser-3-and-tiled-building-a-platformer)
- [Tiled 프로그램](https://www.mapeditor.org/)
- Map에 적용한 디자인 패턴을 완전히 바꿔야할 수 있음

**Comment by KangJiJi** [comment]
@joi0104

**Comment by joi0104** [comment]
와 이거 진짜 좋네요.. 안그래도 map을 조작하는게 어려웠었는데 tile 쓰면 맵을 조작하기에도 더 쉬울 것 같네여 👍
