### ISSUE TITLE
setPosition is not function error는 로컬 컴퓨터 문제인가?

### ISSUE THREAD

**Issue by KangJiJi** [TeamChoiKang/antique-universe-front-end#54]
## 논의 주제

로컬에서 서버를 키고 프론트를 4~5개 쯤 접속하면 가끔 `setPosition`은 함수가 아니라는 에러가 뜨게 된다. 왜 가끔 뜨는지 확실하게 모르겠다.

## 나의 생각

이 에러는 phaser 내부적으로 js를 적용하는 과정에서 에러가 나는 것 같은데 다른 환경(컴퓨터)에서도 실험해볼 필요가 있다.

- 서버를 킨다.
- 5개 이상의 크롬을 열어서 접속해본다.(10개 정도...?)

**Comment by joi0104** [comment]
그러면 main 페이지를 접속하지 않고, 바로 game 페이지에 도입시 위와 같은 에러가 뜨나요?

**Comment by KangJiJi** [comment]
@joi0104 넹. 그런 현상이 간헐적으로 발생합니다.

**Comment by joi0104** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/28296417/128146962-f49c878a-31fd-4749-b2c9-a1d0bc07ac2f.png">
 
 위 코드의 `setPosition`을 불러오는 `characterGroup`가 `undefined`여서 그런거죠? 혹시 움직이지 않을때에도 그런 에러가 뜨나요?

**Comment by KangJiJi** [comment]
![image](https://user-images.githubusercontent.com/22635168/128149011-2ab05f28-7d10-41c9-b121-a900b861ae11.png)

`characterGroup`가 `undefined`여서 그런건지 아니면 현재 캐릭터들이 등록되기 전에 함수를 호출하려고 해서 그러는지는 잘 모르겠습니다. 다만 `undefined`일시 early return을 통해서 방지할 수 있을 것 같네요.

오류를 발생 시키기 위해서는 창을 8개 정도 켜놓고 계속 새로고침 하면 엄청난 렉과 함께 에러가 발생하네요.

**Comment by joi0104** [comment]
ㅠㅠ 저는 시도해봐도 에러가 안뜨네요 ㅠㅜㅠ 나중에 같이 라이브 디버깅 해봐도 좋겠네요..
